### PR TITLE
fix login on defaultRegistry

### PR DESCRIPTION
**Pull request by fahedouch**
fixing https://github.com/containerd/nerdctl/issues/826

`DefaultRegistry`  endpoint should not be converted to hostname in `.docker/config.json` for healthy login process against  https://index.docker.io/v1/

Signed-off-by: fahed dorgaa <fahed.dorgaa@gmail.com>

### CODE REVIEW

**Comment by fahedouch** [comment]
cc @Junnplus

**Comment by fahedouch** [comment]
cc @Junnplus

**Review by Junnplus — APPROVED** [review]
LGTM.

I'm sorry for being late, I've been busy with a new job lately. :)

**Comment by fahedouch** [comment]
@AkihiroSuda can we merge this plz ? Ci failure seems to be unrelated to the PR

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
