### PR TITLE
supporting COMPOSE_FILE environment variable

### PR DESCRIPTION
**Pull request by fahedouch**
fixing https://github.com/containerd/nerdctl/issues/853
Signed-off-by: fahed dorgaa <fahed.dorgaa@gmail.com>

### CODE REVIEW

**Review by Junnplus — APPROVED** [review]
LGTM on green.

**Comment by Junnplus** [comment]
```
=== RUN   TestComposeConfigWithMultipleFile
    compose_config_test.go:112: assertion failed: error is not nil: expected "hello1\nhello2\n", got "hello2\nhello1\n": hello2
        hello1
        
--- FAIL: TestComposeConfigWithMultipleFile (2.57s)
```

**Comment by fahedouch** [comment]
I did split tests because of https://github.com/compose-spec/compose-go/issues/235

**Comment by fahedouch** [comment]
Cc @AkihiroSuda  can we merge this ?

**Review by AkihiroSuda — APPROVED** [review]

**Pull request merged**
