### PR TITLE
mv *.go ./cmd/nerdctl

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Reopen PR #82

- Users using `go install github.com/containerd/nerdctl` will need to change their installation script to  `go install github.com/containerd/nerdctl/cmd/nerdctl`
- Users using `make` or the binary distribution are unaffected

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
cc @06kellyjac  @fahedouch @ktock @fuweid PTAL

**Comment by 06kellyjac** [comment]
You can keep one main.go file in the root to keep the same go install path

something along the lines of this might work (after making Xmain exported):
```
package main

import (
	"github.com/containerd/nerdctl/cmd"
)

func main() {
	if err := cmd.Xmain(); err != nil {
		logrus.Fatal(err)
	}
}
```

**Comment by AkihiroSuda** [comment]
Yes, but it complicates the package structure 😞

**Comment by 06kellyjac** [comment]
> Yes, but it complicates the package structure disappointed

True, you also say using `go install` is not recommended in the README so it's not a big deal causing changes there :+1:

**Review by 06kellyjac — APPROVED** [review]
LGTM

**Review by ktock — APPROVED** [review]

**Comment by fahedouch** [comment]
LGTM

**Pull request merged**
