### PR TITLE
Remove unnecessary lock when printing images/containers

### PR DESCRIPTION
**Pull request by djdongjin**
This PR makes 2 changes:
1. In `compose_images.go`, remove `mutex` by preallocating slice so each `for-loop i` accesses different index of the slice.
2. In `compose_ps.go`, parallel container printing using `errorgroup` and the same improvement as `1`.

Signed-off-by: Jin Dong <jindon@amazon.com>

### CODE REVIEW

**Review by manugupt1 — APPROVED** [review]
Thanks

**Comment by djdongjin** [comment]
> Thanks! Not sure why docker compat tests are failing.

Thanks fore reviewing! The docker compat test seems take too long (exceeds 10 mins). Let me check if there are some tests taking unusually long time.

**Comment by manugupt1** [comment]
> > Thanks! Not sure why docker compat tests are failing.
> 
> Thanks fore reviewing! The docker compat test seems take too long (exceeds 10 mins). Let me check if there are some tests taking unusually long time.

Hm! Where are you getting the 10 mins from? I can't see it here: https://github.com/containerd/nerdctl/blob/main/.github/workflows/test.yml#L159

**Comment by djdongjin** [comment]
> Hm! Where are you getting the 10 mins from? I can't see it here:

`go help testflag` or https://pkg.go.dev/cmd/go/internal/test
```
	-timeout d
	    If a test binary runs longer than duration d, panic.
	    If d is 0, the timeout is disabled.
	    The default is 10 minutes (10m).
```

10 mins matches the docker job error (panic right after 600s):
```
FAIL	github.com/containerd/nerdctl/cmd/nerdctl	600.039s
FAIL
Error: Process completed with exit code 1.
```

**Review by manugupt1 — APPROVED** [review]

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
