### PR TITLE
Use debian base image instead of alpine

### PR DESCRIPTION
**Pull request by manugupt1**
Ensuring ctrd-fuse-overlayfs is present

```
# cat README.md
# nerdctl (full distribution)
- nerdctl: v1.1.0-320-g4349a92
- containerd: v1.6.16
- runc: v1.1.4
- CNI plugins: v1.2.0
- BuildKit: v0.11.2
- Stargz Snapshotter: v0.14.1
- imgcrypt: v1.1.7
- RootlessKit: v1.1.0
- slirp4netns: v1.2.0
- bypass4netns: v0.3.0
- fuse-overlayfs: v1.10
- containerd-fuse-overlayfs: v1.0.5
```

Signed-off-by: Manu Gupta <manugupt1@gmail.com>

### CODE REVIEW

**Comment by manugupt1** [comment]
The benefits are not significant in terms of latency.

**Comment by AkihiroSuda** [comment]
> Ensuring ctrd-fuse-overlayfs is present

Sorry what do you mean, and how it is relevant to the distro?

**Comment by AkihiroSuda** [comment]
I feel glibc is less stable for static linking, and may produce `statically linked applications requires at runtime the shared libraries from the glibc version used for linking` issues for some programs.

So I'd prefer to adhere to musl (Alpine) unless there is a strong reason

**Comment by manugupt1** [comment]
Makes sense! I was trying to optimize CI times. I will
Close it.

**Pull request closed without merging**
