### PR TITLE
[release/1.7] build(deps): bump github.com/containerd/continuity from 0.4.3 to 0.4.4 

### PR DESCRIPTION
**Pull request by sondavidb**
Cherry-picked from https://github.com/containerd/nerdctl/pull/3605

This fix includes a bug where `fs.CopyDir()` would fail on layers without xattr support (ref: https://github.com/containerd/continuity/issues/244).

Aside from fixing issues on older filesystems, any FUSE-based filesystems (e.g. SOCI snapshotter's snapshots) experience notable performance benefits without having to use expensive xattr operations. Thus, it would be helpful to have this bugfix backported to 1.7.

The actual cherry-pick didn't include some of the other dependency bumps included in `go get github.com/containerd/continuity@v0.4.4` so ~I added an extra commit where~ I ran `go mod tidy`.

If desired, I can also backport the bump to v0.4.5 (i.e. commit 32de57ba7a6831c0d33b9714a329689e5d888ea8).

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
You can squash the commits

**Comment by sondavidb** [comment]
Flakes?

**Comment by apostasie** [comment]
> Flakes?

Yeah, very likely - it is the 1.7 branch right?
Let's rerun them and see.

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
