### PR TITLE
feat: add `stats` command to `container`

### LINKED ISSUE #2393: `nerdctl container stats` is missing
The canonical form of `nerdctl stats` should be `nerdctl container stats`, just as in `docker stats` and `docker container stats`

### PR DESCRIPTION
**Pull request by suyanhanx**
close #2393

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by AkihiroSuda** [comment]
```
=== RUN   TestStats
    container_stats_linux_test.go:45: assertion failed: 
        Command:  /usr/bin/docker container stats --no-stream
        ExitCode: 0
        Stdout:   CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O   PIDS
        
        Stderr:   
        
        Failures:
        Expected stdout to contain "nerdctl-test"
--- FAIL: TestStats (6.40s)
```
https://github.com/containerd/nerdctl/actions/runs/5676272811/job/15403686941?pr=2395

**Comment by suyanhanx** [comment]
> ```
> === RUN   TestStats
>     container_stats_linux_test.go:45: assertion failed: 
>         Command:  /usr/bin/docker container stats --no-stream
>         ExitCode: 0
>         Stdout:   CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O   PIDS
>         
>         Stderr:   
>         
>         Failures:
>         Expected stdout to contain "nerdctl-test"
> --- FAIL: TestStats (6.40s)
> ```
> https://github.com/containerd/nerdctl/actions/runs/5676272811/job/15403686941?pr=2395

I tried this test case locally and it works fine.  Could you please rerun it?

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
