### PR TITLE
fix(hosts): Fix hosts file rewrite

### PR DESCRIPTION
**Pull request by tosone**
Before hosts file will rewrite before each container start, extra_hosts cannot write to hosts.

``` yaml
version: '2'
services:
  nginx-1:
    image: nginx:alpine
    container_name: nginx-1
    restart: always
  nginx-2:
    image: nginx:alpine
    container_name: nginx-2
    restart: always
    extra_hosts:
      - "test.example.io:172.19.39.1"
```

We should rewrite the host with the last hosts record.

### CODE REVIEW

**Comment by tosone** [comment]
Windows compile error will fix here: https://github.com/jaytaylor/go-hostsfile/pull/7

**Comment by AkihiroSuda** [comment]
> Signed-off-by: tosone

Thanks, but please use real name for signing

**Comment by tosone** [comment]
@AkihiroSuda windows compile error fixed. Please review again. ^_^

**Comment by AkihiroSuda** [comment]
Thanks, but `go mod tidy` seems needed to pass CI

**Review by AkihiroSuda — APPROVED** [review]
Thanks.

Next time please consider adding an integration test

**Pull request merged**
