### PR TITLE
docs/registry.md: add guide for managed services (ECR, ACR, Docker Hub, GHCR, pkg.dev, GCR, quay.io)

### PR DESCRIPTION
**Pull request by AkihiroSuda**
- [x] ECR
- [x] ACR
- [X] Docker Hub
- [X] GHCR
- [X] pkg.dev
- [X] GCR
- [X] Quay.io

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
I'll release v0.16.1 after merging this

**Comment by fahedouch** [comment]
@AkihiroSuda  would you plz add `JFrog Artifactory` 

tested with a `fahed.jfrog.io/fahedouch-00/alpine`  

test login  --> OK
test push --> OK 
tes pull --> OK

**Comment by AkihiroSuda** [comment]
> would you plz add JFrog Artifactory

I don't have an account, please open a follow-up PR

**Review by fahedouch — APPROVED** [review]

**Comment by fahedouch** [comment]
> I'll release v0.16.1 after merging this

let me making a follow-up PR before releasing `v0.16.1` please

**Pull request merged**
