### PR TITLE
support workaround rootless loopback listening

### PR DESCRIPTION
**Pull request by fahedouch**
fixing  https://github.com/containerd/nerdctl/issues/86

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
I'd rather prefer:
- https://github.com/containerd/nerdctl/issues/814

**Comment by fahedouch** [comment]
> I'd rather prefer:
> 
> * [rootless: run the puller/pusher in the host netns (but still in the userns) #814](https://github.com/containerd/nerdctl/issues/814)

Thanks for your feedback, SGTM

**Comment by fahedouch** [comment]
> I'd rather prefer:
> 
> * [rootless: run the puller/pusher in the host netns (but still in the userns) #814](https://github.com/containerd/nerdctl/issues/814)

@AkihiroSuda  So what you are suggesting is to enable `bypass4nets` to puller/pusher  ?

**Comment by fahedouch** [comment]
are planning to release[v2.0.0](https://github.com/rootless-containers/rootlesskit/releases/tag/v2.0.0-alpha.0) soon ?

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda are planning to release rootlesskit [v2.0.0](https://github.com/rootless-containers/rootlesskit/releases/tag/v2.0.0-alpha.0) in the next few days ?

We need at least a few weeks to experiment detach-netns with nerdctl before releasing RootlessKit v2 GA.

**Comment by fahedouch** [comment]
> > @AkihiroSuda are planning to release rootlesskit [v2.0.0](https://github.com/rootless-containers/rootlesskit/releases/tag/v2.0.0-alpha.0) in the next few days ?
> 
> We need at least a few weeks to experiment detach-netns with nerdctl before releasing RootlessKit v2 GA.

OK so let me integrated the `--detach-netns` to nerdctl

**Comment by AkihiroSuda** [comment]
#2723 will be ready soon, so let me close this

**Pull request closed without merging**
