### PR TITLE
update containerd (v1.5.5), slirp4netns (v1.1.12), fuse-overlayfs (v1.7), RootlessKit (v0.14.4)

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Review by ktock — APPROVED** [review]
LGTM on green.

**Comment by AkihiroSuda** [comment]
Seems regression in RootlessKit v0.14.3

```
$ go test -v -run TestPush ./cmd/nerdctl
test target: "nerdctl"
=== RUN   TestPushPlainHTTPFails
    push_test.go:78: hostIP="192.168.60.11", listenIP="0.0.0.0", listenPort=5000
    push_test.go:194: testImageRef="192.168.60.11:5000/test-push-plain-http-fails:3.13-org"
    push_test.go:199: result: exitCode=1, out="index-sha256:841830f4e8b16e3bfec87ffc70854211399bbe4324b4e109944f8ec3716af0e7:    waiting        |\x1b[32m\x1b[0m--------------------------------------| \nmanifest-sha256:e103c1b4bf019dc290bcc7aca538dc2bf7a9d0fc836e186f5fa34945c5168310: waiting        |\x1b[32m\x1b[0m--------------------------------------| \nlayer-sha256:ca3cd42a7c9525f6ce3d64c1a70982613a8235f0cc057ec9244052921853ef15:    waiting        |\x1b[32m\x1b[0m--------------------------------------| \nconfig-sha256:49f356fa4513676c5e22e3a8404aad6c7262cc7aaed15341458265320786c58c:   waiting        |\x1b[32m\x1b[0m--------------------------------------| \nelapsed: 0.1 s                                                                    total:   0.0 B (0.0 B/s)                                         \ntime=\"2021-08-04T15:04:39+09:00\" level=info msg=\"pushing as a single-platform image (application/vnd.docker.distribution.manifest.list.v2+json, sha256:841830f4e8b16e3bfec87ffc70854211399bbe4324b4e109944f8ec3716af0e7)\"\ntime=\"2021-08-04T15:04:39+09:00\" level=error msg=\"server \\\"192.168.60.11:5000\\\" does not seem to support HTTPS\" error=\"failed to do request: Head \\\"https://192.168.60.11:5000/v2/test-push-plain-http-fails/blobs/sha256:ca3cd42a7c9525f6ce3d64c1a70982613a8235f0cc057ec9244052921853ef15\\\": http: server gave HTTP response to HTTPS client\"\ntime=\"2021-08-04T15:04:39+09:00\" level=info msg=\"Hint: you may want to try --insecure-registry to allow plain HTTP (if you are in a trusted network)\"\ntime=\"2021-08-04T15:04:39+09:00\" level=fatal msg=\"failed to do request: Head \\\"https://192.168.60.11:5000/v2/test-push-plain-http-fails/blobs/sha256:ca3cd42a7c9525f6ce3d64c1a70982613a8235f0cc057ec9244052921853ef15\\\": http: server gave HTTP response to HTTPS client\"\n"
--- PASS: TestPushPlainHTTPFails (7.67s)
=== RUN   TestPushPlainHTTPLocalhost
    push_test.go:78: hostIP="192.168.60.11", listenIP="0.0.0.0", listenPort=5000
    push_test.go:86: assertion failed: expression is false: res.ExitCode == exitCode: time="2021-08-04T15:04:45+09:00" level=fatal msg="failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: time=\"2021-08-04T15:04:45+09:00\" level=fatal msg=\"listen tcp 0.0.0.0:5000: bind: address already in use\"\nFailed to write to log, write /home/suda/.local/share/nerdctl/1935db59/containers/nerdctl-test/a313f205f23c1e445dec0a3d6f38e631109687452c153e58458080e17864933d/oci-hook.createRuntime.log: file already closed: unknown"
        
--- FAIL: TestPushPlainHTTPLocalhost (0.68s)
=== RUN   TestPushPlainHTTPInsecure
    push_test.go:78: hostIP="192.168.60.11", listenIP="0.0.0.0", listenPort=5000
    push_test.go:86: assertion failed: expression is false: res.ExitCode == exitCode: time="2021-08-04T15:04:46+09:00" level=fatal msg="failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: time=\"2021-08-04T15:04:46+09:00\" level=fatal msg=\"listen tcp 0.0.0.0:5000: bind: address already in use\"\nFailed to write to log, write /home/suda/.local/share/nerdctl/1935db59/containers/nerdctl-test/b2be38fe0c6fdfe3dbc60a3571d593a0b26722c776339e5170e9159fa4ac3f25/oci-hook.createRuntime.log: file already closed: unknown"
        
--- FAIL: TestPushPlainHTTPInsecure (0.66s)
=== RUN   TestPushInsecureWithLogin
    push_test.go:106: hostIP="192.168.60.11", listenIP="0.0.0.0", listenPort=5000, authPort=5001
    push_test.go:166: assertion failed: expression is false: res.ExitCode == exitCode: time="2021-08-04T15:04:47+09:00" level=fatal msg="failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: time=\"2021-08-04T15:04:47+09:00\" level=fatal msg=\"listen tcp 0.0.0.0:5000: bind: address already in use\"\nFailed to write to log, write /home/suda/.local/share/nerdctl/1935db59/containers/nerdctl-test/6e0cdc73273e9153ab6d227574d3732bdd1af5770b4fbad7fccef24bfeedce8a/oci-hook.createRuntime.log: file already closed: unknown"
        
--- FAIL: TestPushInsecureWithLogin (1.51s)
FAIL
FAIL    github.com/containerd/nerdctl/cmd/nerdctl       10.543s
FAIL
```

**Comment by AkihiroSuda** [comment]
Updated RootlessKit to v0.14.4

**Comment by fahedouch** [comment]
LGTM

**Pull request merged**
