### PR TITLE
Add GitLab Container Registry to Registry Docs

### PR DESCRIPTION
**Pull request by gaffneyd4**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Thanks, but please sign the commit for DCO
https://github.com/apps/dco

(run `git commit -a -s --amend`, and make sure that the `Signed-off-by: NAME <EMAIL>` line with your real name is included in the commit message)

**Comment by gaffneyd4** [comment]
@AkihiroSuda done

**Comment by fahedouch** [comment]
@gaffneyd4 would you please squash commits

**Comment by gaffneyd4** [comment]
@fahedouch done

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Review by junnplus — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
