### PR TITLE
Fix wrong package import

### LINKED ISSUE #3048: dockerconfigresolver is using the wrong package for errdefs
### Description

https://github.com/containerd/nerdctl/blob/main/pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go#L33

Should be: `github.com/containerd/containerd/errdefs`

This is causing downstream issues wrt hosts.toml file resolution as `errdefs.IsNotFound` never succeeds.

### Steps to reproduce the issue

n.a.

### Describe the results you received and expected

n.a.

### What version of nerdctl are you using?

1.7.6

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by apostasie**
Fix #3048 

ping @AkihiroSuda @ktock @Zheaoli

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
Thanks

Maybe we should have a test

**Comment by apostasie** [comment]
> Thanks
> 
> Maybe we should have a test

Yes, I am going to revamp the login tests soon.

**Comment by apostasie** [comment]
@AkihiroSuda when is 2.0.0? Are we waiting for containerd/2.0?

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda when is 2.0.0? Are we waiting for containerd/2.0?

Yes

**Pull request merged**
