### PR TITLE
cmd/nerdctl: simplify --help

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Before:
```console
$ nerdctl info --help
Display system-wide information

Usage:
  nerdctl info [flags]
Commands:
Flags:
  -f, --format string   Format the output using the given Go template, e.g, '{{json .}}'
  -h, --help            help for info
      --mode string     Information mode, "dockercompat" for Docker-compatible output, "native" for containerd-native output (default "dockercompat")
Global Flags:
      --address string           containerd address, optionally with "unix://" prefix [$CONTAINERD_ADDRESS] (default "/run/containerd/containerd.sock")
      --cgroup-manager string    Cgroup manager to use ("cgroupfs"|"systemd") (default "systemd")
      --cni-netconfpath string   cni config directory [$NETCONFPATH] (default "/home/suda/.config/cni/net.d")
      --cni-path string          cni plugins binary directory [$CNI_PATH] (default "/opt/cni/bin")
      --data-root string         Root directory of persistent nerdctl state (managed by nerdctl, not by containerd) (default "/home/suda/.local/share/nerdctl")
      --debug                    debug mode
      --debug-full               debug mode (with full output)
      --experimental             Control experimental: https://github.com/containerd/nerdctl/blob/master/docs/experimental.md [$NERDCTL_EXPERIMENTAL] (default true)
      --host string              Alias of --address (default "/run/containerd/containerd.sock")
      --hosts-dir strings        A directory that contains <HOST:PORT>/hosts.toml (containerd style) or <HOST:PORT>/{ca.cert, cert.pem, key.pem} (docker style) (default [/home/suda/.config/containerd/certs.d,/home/suda/.config/docker/certs.d])
      --insecure-registry        skips verifying HTTPS certs, and allows falling back to plain HTTP
      --namespace string         containerd namespace, such as "moby" for Docker, "k8s.io" for Kubernetes [$CONTAINERD_NAMESPACE] (default "default")
      --snapshotter string       containerd snapshotter [$CONTAINERD_SNAPSHOTTER] (default "overlayfs")
      --storage-driver string    Alias of --snapshotter (default "overlayfs")
```

After:
```console
$ nerdctl info --help
Display system-wide information

Usage: nerdctl info [flags]

Flags:
  -f, --format string   Format the output using the given Go template, e.g, '{{json .}}'
  -h, --help            help for info
      --mode string     Information mode, "dockercompat" for Docker-compatible output, "native" for containerd-native output (default "dockercompat")

See also 'nerdctl --help' for the global flags such as '--namespace', '--snapshotter', and '--cgroup-manager'.
```

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
cc @mook-as @jandubois , this may break https://github.com/rancher-sandbox/rancher-desktop/commits/main/src/go/nerdctl-stub

**Review by manugupt1 — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
@mook-as @jandubois 
Can we merge this soon, or do you want us to postpone this to v0.24?

**Comment by AkihiroSuda** [comment]
cc @containerd/nerdctl-maintainers , I'd like to release v0.23 soon, right after deciding whether to merge this or not

**Comment by jandubois** [comment]
> Can we merge this soon, or do you want us to postpone this to v0.24?

I've talked with @mook-as, and we are fine with merging it now.

**Review by Zheaoli — APPROVED** [review]
LGTM,Thanks!

**Review by ktock — APPROVED** [review]

**Pull request merged**
