### PR TITLE
Setup nerdctl top cmd

### PR DESCRIPTION
**Pull request by fahedouch**
same as `docker top` 

Signed-off-by: fahed dorgaa <fahed.dorgaa@gmail.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Ideally we should use github.com/containers/psgo rather than exec-ing `ps`, but this refactoring can be done later.

**Comment by fahedouch** [comment]
running the ps command in a rootless container with cgroupv1 is not possible because rootless container does not rely on cgroupv1.
the problem does not arise in the case of rootlfull (v1 or v2) && rootless ( v2) 
The idea to get around this problem is to join the mount namespace of rootless container when we are dealing with rootless container on cgroupv1 and fetch process info inside the pid mount ns. 

FYI : for pid host is like doing a ps on the host and dealing with the host `/proc` so we should add this to the condition when implementing ` --pid=host`

I prefer making this refactoring later when using `psgo` rather than exec-ing ps. It handles better this use cases.

**Comment by fahedouch** [comment]
Cc @AkihiroSuda

**Review by AkihiroSuda — APPROVED** [review]
LGTM if green, thanks

**Comment by fahedouch** [comment]
Pid host is implemented here https://github.com/containerd/nerdctl/pull/273
The case of host pid should be handled when refacto with psgo

**Pull request merged**
