### PR TITLE
MAINTAINERS: add Kay Yan (yankay) as a REVIEWER

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Kay Yan (@yankay) has been very actively contributing to the project:
https://github.com/containerd/nerdctl/pulls?q=author%3Ayankay+

So I'd like to invite @yankay as a reviewer

Needs explicit LGTM from @yankay and 1/3 of the nerdctl Committers ( $ceil \left( 4 \times \frac{1}{3} \right) = 2$ ), according to
https://github.com/containerd/project/blob/main/GOVERNANCE.md :

> After a candidate has been informally proposed in the maintainers forum, the
existing maintainers are given seven days to discuss the candidate, raise
objections and show their support. Formal voting takes place on a pull request
that adds the contributor to the MAINTAINERS file. Candidates must be approved
by 2/3 of the current committers by adding their approval or LGTM to the pull
request. The reviewer role has the same process but only requires 1/3 of current
committers.
> If a candidate is approved, they will be invited to add their own LGTM or
approval to the pull request to acknowledge their agreement. A committer will
verify the numbers of votes that have been received and the allotted seven days
have passed, then merge the pull request and invite the contributor to the
organization.
> For non-core sub-projects, only committers of the repository that the candidate
is proposed for are given votes.

- [x] @yankay
- [x] @AkihiroSuda ([core committer, so *non*-binding](https://github.com/containerd/project/blob/e31a9f12ce6dec1b4df2b37fb1caa6cbdf4e58b6/GOVERNANCE.md#adding-maintainers))
- [x] @fahedouch 
- [x] @ktock
- [ ] @junnplus 
- [x] @Zheaoli 

I'd also like to get a few LGTMs from the Core Committers too. (not necessary)

This PR will remain open for 7 days.

### CODE REVIEW

**Review by Zheaoli — APPROVED** [review]
LGTM,Welcome!

**Comment by yankay** [comment]
Thanks 

It's my pleasure to contribute to the nerdctl :-) 
And I want to try my best to work as a reviewer :-)

LGTM

**Review by yankay — APPROVED** [review]

**Review by ktock — APPROVED** [review]
LGTM

**Review by fahedouch — APPROVED** [review]
Welcome :)

**Comment by AkihiroSuda** [comment]
Sent  a GitHub invitation to @yankay

**Comment by yankay** [comment]
> Sent a GitHub invitation to @yankay

Thanks @AkihiroSuda, @Zheaoli , @ktock , @fahedouch 

I'll try my best  :-)

**Comment by AkihiroSuda** [comment]
@yankay "yankay" on `cloud-native.slack.com` is your account?
(Sorry, forgot to invite you to the private maintainer channel.)

**Comment by yankay** [comment]
HI @AkihiroSuda 
yankay on `cloud-native.slack.com` is my account. Thanks :-)

**Pull request merged**
