### PR TITLE
Login refactor (small breakout): hostsstore resolution cleanup

### LINKED ISSUE #3047: hosts.toml file resolution does not seem to account for default port being ommitted
### Description

`nerdctl login https://foo:443`
vs.
`nerdctl login https://foo`

If the `hosts.toml` path contains the port, the second one will fail.
On the other hand, if it does not, the first one will fail.

Responsibility for walking the host dir is in `dockerconfigresolver.go` (NewHostOptions > HostDir()).
This does not try to be smart wrt what the host contains (port or no port).

We should patch this so:
- if scheme is https, passing :443 or not passing it should work
- ~~all of this should work with hosts.toml files path containing the port or not~~

### Steps to reproduce the issue

See description

### Describe the results you received and expected

Fail / not fail.

### What version of nerdctl are you using?

1.7.6

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by apostasie**
Fix #3047

Commit message for details.

This is not testable yet (IIRC, because of the way we currently resolve authentication), but I will add tests for this specific condition later on in another upcoming "login" PR.

### CODE REVIEW

**Comment by apostasie** [comment]
CI failure appears to be a network fluke.

**Comment by apostasie** [comment]
Gentle ping on this.
Although there is no rush - as login rewrite is still pending the design document to be reviewed - would be nice to get this in.

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by nakamorichi** [comment]
@apostasie @AkihiroSuda This may have broken repository authentication (currently not able to confirm due to lack of time). 

When doing `nerdctl login`, the repo address in `~/.docker/config.json` ends up with port, and at least authentication to ECR fails. When removing the port manually, ECR auth works. Could be also ECR issue, though. I started experiencing the issue recently, but can't pinpoint exact time or particular change as I upgraded various components in my build environment recently.

**Comment by apostasie** [comment]
@nakamorichi will look asap tomorrow.

**Comment by apostasie** [comment]
@nakamorichi confirming this change here has not made it to any rc.
I would still like to look into your problem.
Can you open an issue with details on how to reproduce?

thanks

**Comment by apostasie** [comment]
@nakamorichi 
Using the latest main, things work for me with the following:

```
aws ecr-public get-login-password --region us-east-1 | nerdctl login --username AWS --password-stdin public.ecr.aws
```

If you are still facing issues, as suggested, you should open a new ticket, with details on what exactly you are doing / how to reproduce.
Thanks.

**Comment by nakamorichi** [comment]
@apostasie Understood. I'll see if I can find a way to reproduce it. Btw, I'm using lima on macOS Sequoia, but I'm not sure how it could have impact in this case.

**Comment by apostasie** [comment]
> @apostasie Understood. I'll see if I can find a way to reproduce it. Btw, I'm using lima on macOS Sequoia, but I'm not sure how it could have impact in this case.

Am on Lima too (and whatever is macOS latest).
I do not think it would - very curious about your problem though - lmk if you investigate more)

**Pull request merged**
