### PR TITLE
rootless: support stargz

### PR DESCRIPTION
**Pull request by AkihiroSuda**
See `./docs/rootless.md` for the usage.

Stargz Snapshotter <= 0.4.1 only works on Ubuntu and Debian kernel.
Future versions will work on any distro with kernel >= 4.18.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
cc @ktock

**Comment by ktock** [comment]
@AkihiroSuda Tried this rootless mode on ubuntu 20.10 and it works even with mainline linux 5.11.

<details>
<summary>setup procedure</summary>

<pre>
<code>

sudo apt-get install -y make jq gcc slirp4netns uidmap dbus-user-session rootlesskit

# Install deps (go, containerd, runc, cni, stargz snapshotter)

cd ~

wget https://golang.org/dl/go1.16.2.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.16.2.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
go version

wget https://github.com/containerd/containerd/releases/download/v1.5.0-beta.4/containerd-1.5.0-beta.4-linux-amd64.tar.gz
tar zxvf containerd-1.5.0-beta.4-linux-amd64.tar.gz
sudo install ./bin/* /usr/local/bin

wget https://github.com/opencontainers/runc/releases/download/v1.0.0-rc93/runc.amd64
sudo install ./runc.amd64 /usr/local/bin/runc

sudo mkdir -p /opt/cni/bin
curl -Ls https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz | sudo tar xzv -C /opt/cni/bin

mkdir -p ~/go/src/github.com/containerd/
cd ~/go/src/github.com/containerd/

git clone https://github.com/containerd/stargz-snapshotter
cd stargz-snapshotter
make -j4
sudo make install

# Install nerdctl and run rootless containerd

cd ../
git clone https://github.com/AkihiroSuda/nerdctl
cd nerdctl
git checkout c13ce2e5c1719b931a9154b76748edf114e75f16
sed -i 's/--port-driver=builtin/--port-driver=slirp4netns/g' ./extras/rootless/containerd-rootless-setuptool.sh
make
sudo make install

containerd-rootless-setuptool.sh install
sleep 3
containerd-rootless-setuptool.sh install-stargz
cat <<EOF > ~/.config/containerd/config.toml
[proxy_plugins]
  [proxy_plugins."stargz"]
      type = "snapshot"
      address = "/run/user/$(id -u | tr -d '\n')/containerd-stargz-grpc/containerd-stargz-grpc.sock"
EOF
sleep 3
systemctl --user restart containerd.service
export CONTAINERD_SNAPSHOTTER=stargz
sleep 3
nerdctl run -it --rm ghcr.io/stargz-containers/python:3.9-esgz sh -ec "apt-get update && apt-get install -y sl"

</code>
</pre>
</details>

P.S.
Though I haven't looked it deeper, `sed -i 's/--port-driver=builtin/--port-driver=slirp4netns/g' ./extras/rootless/containerd-rootless-setuptool.sh` was needed for my setup with Ubuntu 20.10 (`Linux ktock 5.8.0-45-generic #51-Ubuntu SMP Fri Feb 19 13:24:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`).

Otherwise I got 

```
[INFO] Checking RootlessKit functionality
[rootlesskit:parent] error: dial unix /tmp/rootlesskit928318489/.bp.sock: connect: no such file or directory
[ERROR] RootlessKit failed, see the error messages and https://rootlesscontaine.rs/getting-started/common/ .
```

**Comment by AkihiroSuda** [comment]
> .bp.sock: connect: no such file or directory

This is a known flakiness, could you retry several times

**Review by ktock — APPROVED** [review]
> .bp.sock: connect: no such file or directory

#126 solves it.

**Comment by ktock** [comment]
FYI: Released stargz snapshotter v0.5.0 with rootless support: https://github.com/containerd/stargz-snapshotter/releases/tag/v0.5.0

**Comment by AkihiroSuda** [comment]
Updated for v0.5.0. Still LGTY?

**Review by ktock — APPROVED** [review]

**Pull request merged**
