### PR TITLE
3452: Filter Volumes by name if any of the names match

### LINKED ISSUE #3452: volume (probably others) `filter` behavior is inconsistent with Docker
### Description

```
docker volume create foo1
docker volume create foo2
docker volume ls --quiet --filter name=foo1 --filter name=foo2
```

vs.

```
nerdctl volume create foo1
nerdctl volume create foo2
nerdctl volume ls --quiet --filter name=foo1 --filter name=foo2
```

Docker does "or", nerdctl does "and".

Discovered while rewriting the volume tests with the new tooling.

### Steps to reproduce the issue

na

### Describe the results you received and expected

na

### What version of nerdctl are you using?

na

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by manugupt1**
Fixes #3452

### CODE REVIEW

**Comment by apostasie** [comment]
@manugupt1 CI is bust rn - #3479 

Looking into it now.

**Comment by manugupt1** [comment]
@apostasie no worries! take your time.

**Comment by manugupt1** [comment]
Cc @apostasie fyi! Ty for your help

**Review by apostasie — APPROVED** [review]

**Comment by apostasie** [comment]
> Cc @apostasie fyi! Ty for your help

Yw!
Thanks for fixing this issue @manugupt1 - LGTM.

cc @djdongjin @AkihiroSuda

**Review by djdongjin — APPROVED** [review]
LGTM thanks

**Pull request merged**
