### PR TITLE
Rewrite container remove

### PR DESCRIPTION
**Pull request by apostasie**
This is initially motivated by #3134 

Currently `container.Remove` is faulty as it starts removing resources (specifically anonymous volumes) before even confirming that the container **should** be removed.

There are other likely issues with the current implementation - there seem to be cases where we delete the container, but do not cleanup networking on windows - and likely different behavior wrt snapshot cleanups dependent on container status.

Overall, this function is complex to reason about, because of the defer, the named return value, the confusing logic in what should happen when and what is a hard error or not.
All these reasons explain why the mistakes / issues were made in the first place.

This PR is a suggested rewrite, with the following objectives:
- make it (a little bit) simpler to reason about
- comment generously
- make variables names easier to read
- fix the issues

I appreciate this is impactful, but I also do not think we are quite done here and there may be more bugs in the overall container lifecycle when it comes to destruction.

Nevertheless - this is definitely fixing the core problem which is pretty bad (deletion of anonymous volumes for containers that should not be deleted).

This is draft until the CI is green (can't test windows here).

### CODE REVIEW

**Comment by apostasie** [comment]
cc @AkihiroSuda PTAL at your convenience.
Windows is failing for now but does not seem related? (can you poke it?)

**Review by AkihiroSuda — APPROVED** [review]
Thanks, can we have a test?

**Comment by apostasie** [comment]
@AkihiroSuda sure - sorry for not doing it in the first place, I was in a rush.

Added a test for #3134

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
