### PR TITLE
image: dedup same platform entry

### PR DESCRIPTION
**Pull request by zhuangqh**
may got duplicate value from image.Platforms interface.
we should duplicate them like ctr do

Signed-off-by: zhuangqh <zhuangqhc@gmail.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
How to repro the issue?

**Comment by zhuangqh** [comment]
> How to repro the issue?

when listing image which was generated from criu checkpoint.  see https://github.com/containerd/containerd/issues/9081

**Comment by AkihiroSuda** [comment]
Windows test is failing
```
=== CONT  TestImagesWithNames
    image_list_test.go:36: assertion failed: 
        Command:  C:\Users\runneradmin\go\bin\nerdctl.exe --namespace=nerdctl-test images --names gcr.io/k8s-staging-e2e-test-images/busybox:1.29-2
        ExitCode: 0
        Stdout:   NAME    IMAGE ID    CREATED    PLATFORM    SIZE    BLOB SIZE
        
        Stderr:   
        
        Failures:
        Expected stdout to contain "gcr.io/k8s-staging-e2e-test-images/busybox:1.29-2"
--- FAIL: TestImagesWithNames (0.55s)
```
https://github.com/containerd/nerdctl/actions/runs/6146430040/job/16700918243?pr=2486

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by zhuangqh** [comment]
@AkihiroSuda I have no idea whether to dudup inside the `image.Platform()` implementation or here. What do you recommend

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda I have no idea whether to dudup inside the `image.Platform()` implementation or here. What do you recommend

Ideally deduplication should happen in `image.Platform()`

**Comment by zhuangqh** [comment]
> 

ok, I'm committing changes to the upstream containerd repository. So hold this pr, thanks

**Comment by zhuangqh** [comment]
Still dedup here as a workaround, see https://github.com/containerd/containerd/issues/9081#issuecomment-1729866176
thanks  @AkihiroSuda

**Comment by AkihiroSuda** [comment]
Thanks, merged

**Pull request merged**
