### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by ameir**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Thanks, but please sign the commit with real name
https://github.com/apps/dco

**Comment by AkihiroSuda** [comment]
Ping @ameir

**Review by joubertredrat — APPROVED** [review]

**Comment by ameir** [comment]
@AkihiroSuda I have re-pushed with a signature. Please let me know if you need anything further.

**Review by AkihiroSuda — APPROVED** [review]
thanks

**Pull request merged**
