### PR TITLE
Fixed gosimple errors in issue #1134

### PR DESCRIPTION
**Pull request by sondavidb**
#1134 

Fixed all the cases mentioned in the above issue.

Worth noting that running the same command used in the issue on my machine brought up some other errors that were not related to `gosimple`, but also a couple extra that were not highlighted in the issue. The former I left untouched but the latter I fixed up and you can see them in `stats.go`.

This is now what shows when running the command:

```
$ golangci-lint run -E "gosimple"
cmd/nerdctl/pull_linux_test.go:66:4: t.Setenv undefined (type *testing.T has no field or method Setenv) (typecheck)
        t.Setenv("COSIGN_PASSWORD", "1")
          ^
cmd/nerdctl/pull_linux_test.go:122:4: t.Setenv undefined (type *testing.T has no field or method Setenv) (typecheck)
        t.Setenv("COSIGN_PASSWORD", "1")
          ^
cmd/nerdctl/pull_linux_test.go:148:4: t.Setenv undefined (type *testing.T has no field or method Setenv) (typecheck)
        t.Setenv("COSIGN_PASSWORD", "2")
```

Signed-off-by: David Son <davbson@amazon.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Thanks, could you enable gosimple in `.golangci.yaml` ?

https://github.com/containerd/nerdctl/blob/99b12ddc2ae7d58710cc171dc4b46235c9ee2982/.golangci.yml#L47

**Comment by AkihiroSuda** [comment]
> t.Setenv undefined

Probably your Go is old.
Please make sure to use Go 1.18.

**Comment by sondavidb** [comment]
>

**Comment by sondavidb** [comment]
> > t.Setenv undefined
> 
> Probably your Go is old. Please make sure to use Go 1.18.

Sorry, misclick. Wanted to confirm that updating to Go 1.18 eliminated the errors.

**Comment by sondavidb** [comment]
Sorry to leave this hanging for this long, I did poke into it a bit more but couldn't seem to figure out why the tests failed. Today I noticed you guys added a label and it seems to be related to flaky testing. Would you like me to continue prodding around this commit, or are you guys fairly sure that it's an issue with the tests versus my (supposedly) semantic changes?

**Comment by AkihiroSuda** [comment]
CI is green after restarting.
Could you rebase and update .golangci.yml? Then LGTM

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
