### PR TITLE
remove scope for registry login

### PR DESCRIPTION
**Pull request by Junnplus**
Signed-off-by: ye.sijun <junnplus@gmail.com>

Fixes: https://github.com/containerd/nerdctl/issues/717

### CODE REVIEW

**Comment by Junnplus** [comment]
```
panic: runtime error: slice bounds out of range [:1] with capacity 0

goroutine 1 [running]:
github.com/containerd/containerd/remotes/docker.GetTokenScopes({0x15a4338, 0xc00003e0a0}, {0x0, 0x0, 0x0})
        /home/jun.linux/go/pkg/mod/github.com/containerd/containerd@v1.6.0-beta.5.0.20220106193438-3ccd43c8f685/remotes/docker/scope.go:96 +0x28f
github.com/containerd/containerd/remotes/docker.(*authHandler).doBearerAuth(0xc0001c4a20, {0x15a4338, 0xc00003e0a0})
        /home/jun.linux/go/pkg/mod/github.com/containerd/containerd@v1.6.0-beta.5.0.20220106193438-3ccd43c8f685/remotes/docker/authorizer.go:274 +0xb9
github.com/containerd/containerd/remotes/docker.(*authHandler).authorize(0xc0000b3900, {0x15a4338, 0xc00003e0a0})
        /home/jun.linux/go/pkg/mod/github.com/containerd/containerd@v1.6.0-beta.5.0.20220106193438-3ccd43c8f685/remotes/docker/authorizer.go:253 +0x39
github.com/containerd/containerd/remotes/docker.(*dockerAuthorizer).Authorize(0xc0000b3900, {0x15a4338, 0xc00003e0a0}, 0xc00003c300)
        /home/jun.linux/go/pkg/mod/github.com/containerd/containerd@v1.6.0-beta.5.0.20220106193438-3ccd43c8f685/remotes/docker/authorizer.go:126 +0x6d
main.tryLoginWithRegHost({0x15a4338, 0xc00003e0a0}, {0xc0002d94a0, {0x158db10, 0xc0000b3900}, {0x7fff8feacda0, 0x21}, {0x1298980, 0x5}, {0x129667c, ...}, ...})
        /Users/jun/Documents/workspace/nerdctl/cmd/nerdctl/login.go:269 +0x2b4
main.loginClientSide({0x15a4338, 0xc00003e0a0}, 0xc00032e780, {{0x7fff8feacdc5, 0x15}, {0x7fff8feacdde, 0xf}, {0x0, 0x0}, {0x0, ...}, ...})
        /Users/jun/Documents/workspace/nerdctl/cmd/nerdctl/login.go:237 +0x7e8
main.loginAction(0xc00032e780, {0xc000403ce0, 0x1, 0x6})
        /Users/jun/Documents/workspace/nerdctl/cmd/nerdctl/login.go:101 +0x290
github.com/spf13/cobra.(*Command).execute(0xc00032e780, {0xc00003a0a0, 0x6, 0x6})
        /home/jun.linux/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00037fb80)
        /home/jun.linux/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/jun.linux/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.xmain()
        /Users/jun/Documents/workspace/nerdctl/cmd/nerdctl/main.go:85 +0x9f
main.main()
        /Users/jun/Documents/workspace/nerdctl/cmd/nerdctl/main.go:68 +0x19
```

**Comment by AkihiroSuda** [comment]
@Junnplus https://github.com/containerd/containerd/pull/6463  seems merged, could you update this PR ?

**Comment by Junnplus** [comment]
@AkihiroSuda Updated, but need help. Run action containerd/project-checks failed, am i missing something?

```
  To proceed despite packages unresolved in go 1.16:
  	go mod tidy -e
  If reproducibility with go 1.16 is not needed:
  	go mod tidy -compat=1.17
  For other options, see:
  	https://golang.org/doc/modules/pruning
```

**Comment by AkihiroSuda** [comment]
> go mod tidy -compat=1.17

Could you try this?

**Comment by Junnplus** [comment]
> Could you try this?

I mean ci can't green, it's ok locally

**Comment by AkihiroSuda** [comment]
Could you try that command and push to this PR, and see whether CI passes?

**Comment by Junnplus** [comment]
I think it might be related to https://github.com/containerd/project-checks/blob/main/script/validate/vendor#L24

**Pull request merged**
