### PR TITLE
bump up stargz-snapshotter to v0.6.4

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Draft until actual release of v0.6.3
cc @ktock 

I'll release nerdctl v0.8.3 after merging this.

**Comment by AkihiroSuda** [comment]
Ready for review

**Comment by AkihiroSuda** [comment]
```
# github.com/hanwen/go-fuse/v2/fuse
Error: ../../../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/api.go:224:41: undefined: GetAttrIn
Error: ../../../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/api.go:225:41: undefined: SetAttrIn
Error: ../../../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/api.go:228:39: undefined: MknodIn
Error: ../../../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/api.go:252:42: undefined: SetXAttrIn
Error: ../../../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/api.go:258:40: undefined: CreateIn
Error: ../../../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/api.go:260:38: undefined: ReadIn
Error: ../../../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/api.go:269:39: undefined: WriteIn
Error: ../../../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/api.go:278:41: undefined: ReadIn
Error: ../../../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/types.go:550:2: undefined: Attr
Error: ../../../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/types.go:578:2: undefined: Attr
Error: ../../../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/api.go:278:41: too many errors
```

I guess I have to defer this PR after v0.8.3

**Comment by ktock** [comment]
> I guess I have to defer this PR after v0.8.3

Sorry for that. Sure. I'm looking deeper into it.

**Comment by AkihiroSuda** [comment]
The error is only happening for Windows build, so we can fix the issue on this repo

**Comment by ktock** [comment]
This seems because `nativeconverter` imports `go-fuse` via `github.com/containerd/stargz-snapshotter/store` and `go-fuse` doesn't allow to built on windows. https://github.com/containerd/stargz-snapshotter/pull/333 fixes this dependency issue.

Could we release v0.8.3 after containerd/stargz-snapshotter#333  tagged with v0.6.4? Or should we defer this PR after v0.8.3?

**Comment by ktock** [comment]
Released stargz snapshotter v0.6.4 https://github.com/containerd/stargz-snapshotter/releases/tag/v0.6.4

**Comment by AkihiroSuda** [comment]
Thanks, updated to v0.6.4

**Review by ktock — APPROVED** [review]

**Comment by ktock** [comment]
@AkihiroSuda Could we have a new release tag for this commit?

**Pull request merged**
