### PR TITLE
remove is shareable test

### PR DESCRIPTION
**Pull request by Shubhranshu153**
Based on discussions in https://github.com/containerd/nerdctl/issues/3451

### CODE REVIEW

**Comment by Shubhranshu153** [comment]
tentatively created this pull request based on the conversation in https://github.com/containerd/nerdctl/issues/3451#issuecomment-2366912574

technically i dont see the risk as long as builds are successful and that is already tested. 
@apostasie

**Comment by apostasie** [comment]
Thanks @Shubhranshu153 

As outlined in the ticket, I have no gripe against the existence of the test itself :-).

I am fine with removing it of course if it serves no purpose (haven't looked closely into unit tests around that).

**Comment by Shubhranshu153** [comment]
The test is checking if the image built is shareable in case the target platform and the platform it is built on matches, Before the pr we used to tar and load it if the --platform option was provided even if the platform matches for the build system.

@AkihiroSuda  would like some suggestion weather to refactor this test to be more robust (and also fix the bug) or we want to remove it altogether. Unit test are there but the exact test is not there in E2E setup.

**Comment by Shubhranshu153** [comment]
Checking back on this if we want to remove it or refactor it.
Thanks.

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
