### PR TITLE
add attach command

### PR DESCRIPTION
**Pull request by ningmingxiao**
Signed-off-by: ningmingxiao <ning.mingxiao@zte.com.cn>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Thanks, but this needs tests.

Also, I guess we don't support attaching multiple terminals to a single container and we have to document that.

**Comment by ningmingxiao** [comment]
I use nerdctl run a container and then nerdctl attach it,it will not work. 
 but use crictl run a container then nerdctl attach it will work

**Comment by AkihiroSuda** [comment]
> I use nerdctl run a container and then nerdctl attach it,it will not work. but use crictl run a container then nerdctl attach it will work

Please document that in `README.md` and `nerdctl attach --help`

**Comment by fahedouch** [comment]
@ningmingxiao are you planning to continue working ont his PR ?

**Comment by ningmingxiao** [comment]
> @ningmingxiao are you planning to continue working ont his PR ?

when i use nerdctl run a container then i use nerdctl attach it, but it will not work, but if i use crictl run a container nerdctl attach will work well, do you have some advices?

**Comment by junnplus** [comment]
`nerdctl run -d` different from crictl/ctr tools, IO sets of task is a log URI. see https://github.com/containerd/nerdctl/blob/master/pkg/taskutil/taskutil.go#L54-L60

**Comment by AkihiroSuda** [comment]
Closing, as we merged #2108

**Pull request closed without merging**
