### PR TITLE
pkg/defaults: CNI: search /usr/local/lib/cni, ~/.local/lib/cni

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Follow-up to #315

### CODE REVIEW

**Comment by vbatts** [comment]
what distro lands things in these paths?

**Comment by AkihiroSuda** [comment]
Not for any distro, but /usr and /usr/local should be compatible

**Comment by fahedouch** [comment]
FYI : podman is setting `/usr/local/lib/cni` path to look for cni plugin

https://github.com/containers/common/blob/8ca8dd9c0bdfc24e1e91211ec47dfb74d7c36b95/pkg/config/default.go#L82

**Review by vbatts — APPROVED** [review]
Right on. Any time there are a list of paths to search, it's good to know why.
A good next step would be to set order on which is searched. And then log it somewhere the path chosen.

**Pull request merged**
