### PR TITLE
build for macOS

### PR DESCRIPTION
**Pull request by robberphex**
* Now can build nerdctl at macOS.
* `nerdctl version` works at macOS. Other command is WIP.
* Can build debug version via `make nerdctl GOGCFLAGS="all=-N -l" GOLDFLAGS=""`

### CODE REVIEW

**Comment by robberphex** [comment]
This PR depends on https://github.com/containerd/containerd/pull/6393 .

**Comment by AkihiroSuda** [comment]
For what purpose?

**Comment by AkihiroSuda** [comment]
cc @thehajime

Is this PR useful for uKontainer?

**Comment by thehajime** [comment]
> cc @thehajime
> 
> Is this PR useful for uKontainer?

yes.

I actually have played with nerdctl with my WIP branch, connecting with my containerd PR (https://github.com/containerd/containerd/pull/5935).  I was thinking to poke nerdctl after the PR is settled (but not yet so far).

my tentative patch is here: https://github.com/ukontainer/nerdctl/commit/b891739e66183ed7fcb0f1e5d00444cb7dbddd49

**Comment by AkihiroSuda** [comment]
Let me close this in favor of https://github.com/containerd/nerdctl/pull/732 , toward LKL integration

**Pull request closed without merging**
