### PR TITLE
compose: fix bogus warning: `Ignoring: volume: [Volume]`

### LINKED ISSUE #336: [Compose] bogus warning: `Ignoring: volume: [Volume]`
```console
~/gopath/src/github.com/containerd/nerdctl/examples/compose-wordpress$ nerdctl compose up
WARN[0000] Ignoring: volume: [Volume]                   
WARN[0000] Ignoring: volume: [Volume]                   
INFO[0000] Ensuring image wordpress:5.7 
```

The warning is bogus and should be removed.
The volume is actually supported.

ccfe513d4adbf60944f7863792e7540eead6ec87

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #336

### CODE REVIEW

**Review by ktock — APPROVED** [review]

**Comment by fahedouch** [comment]
it looks like we force ignoring `Bind` and `Volumes` right ? can you explain why you made this @AkihiroSuda . Thanks

**Comment by AkihiroSuda** [comment]
We have "Type" field, so we do not need to read Bind and Volme to determine the type.

**Comment by AkihiroSuda** [comment]
PRs are welcome for unimplemented options 😃

**Comment by fahedouch** [comment]
Okey :) . I will open a ticket for this.

**Pull request merged**
