### PR TITLE
Kubernetes minor cleanup (rename and -f on delete)

### PR DESCRIPTION
**Pull request by apostasie**
This is to address @fahedouch belated comments on #3296

Specifically:
- pass `-f` to kubectl delete to speed up the teardown routine
- rename "Kube" to "K8s" for clarity

PTAL at your convenience.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
> rename "Kube" to "K8s" for clarity

Sounds less clear in my feeling

**Comment by apostasie** [comment]
> > rename "Kube" to "K8s" for clarity
> 
> Sounds less clear in my feeling

@fahedouch ^

@AkihiroSuda what about just "kubernetes"? That avoids the possible confusion with kubectl that fahedouch was probably wary of, and is better than k8s.

**Comment by AkihiroSuda** [comment]
SGTM

**Comment by apostasie** [comment]
> SGTM

Ok, should be fine, but let's wait for the kubernetes action to finish.

**Comment by apostasie** [comment]
Failure is unrelated (`TestIPFSComposeUp` which is really driving me totally bonkers)

**Review by fahedouch — APPROVED** [review]
Thanks

**Pull request merged**
