### PR TITLE
Add nerdctl build --add-host option support

### PR DESCRIPTION
**Pull request by austinvazquez**
This change adds support for image build --add-host option to enable custom host-to-IP mappings.

### CODE REVIEW

**Review by pendo324 — APPROVED** [review]

**Review by coderbirju — APPROVED** [review]

**Review by chews93319 — APPROVED** [review]
LGTM

nit/qq: Will the `image build --add-host` need to handle the special 'host-gateway' string?

**Comment by austinvazquez** [comment]
@chews93319, yep good call out. Let me push another revision for this.

**Comment by austinvazquez** [comment]
@chews93319, I pushed https://github.com/containerd/nerdctl/commit/054b6331d972d5a672bf3eda375d454e7d99ba4b which refactors container run --add-host parsing logic into a utility function for host-gateway functionality.

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
